name: Zhihui Xie | Homepage
markdown: kramdown
highlighter: rouge
google_analytics: UA-158801170-1
# plugins:
#   - jekyll-last-modified-at
# last-modified-at:
#   date-format: '%d-%b-%y'
collections:
  publications:
    # output: true
    # permalink: /:collection/:name
